---
## installs and sets up Mariadb
- name: Install MariaDB package
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - mariadb-server
    - python-mysqldb

- name: Start MariaDB Service
  service: name=mysql state=started enabled=yes