---
- name: Transfer backup sql file
  ansible.builtin.copy:
    src: /home/ubuntu/backup.sql
    dest: /home/ubuntu/backup.sql
    owner: root
    group: root
    mode: 0600

- name: Install python module
  apt: name=python3-pymysql state=latest

- name: Install MariaDB.
  apt:
    name:
      - mariadb-server
      - mariadb-client
    state: present
    update_cache: yes
    cache_valid_time: '{{ aptget_update_cache_valid_time }}'

- name: Start and enable MariaDB service
  service:
    name: '{{ mariadb_service_name }}'
    state: started
    enabled: yes

- name: Copy ~/.my.cnf to root.
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Install network configuration file
  template:
    src: settings.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/settings.cnf
    owner: root
    group: root
    mode: 0644
  notify: restart mariadb

- name: Create root user with password
  mysql_user:
    name: root
    host: '{{ item }}'
    password: '{{ mariadb_root_password }}'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Create replication account 
  mysql_user:
    name: repl
    host: "%"
    password: "{{ mariadb_repl_password }}"
    state: present
    priv: "*.*:REPLICATION SLAVE" # ability to read binary log events from master
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create read-write user
  mysql_user: 
    name: rwuser
    host: "%"
    password: "{{ mariadb_rwuser_password }}"
    state: present
    priv: "*.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Delete test database
  mysql_db:
    name: test
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Delete anonymous users
  mysql_user:
    name: ''
    host: '{{ item }}'
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock
  with_items:
    - localhost

- name: Create databases
  mysql_db:
    name: '{{ item }}'
    state: import
    target: /home/ubuntu/backup.sql
    login_unix_socket: /var/run/mysqld/mysqld.sock
  with_items:
    - '{{ mariadb_databases }}'

- name: Grant access for all wordpress hosts
  mysql_user:
    name: 'client'
    password: 'changeme'
    host: '%'
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
# - name: Update wp hostname to loadbalancer floating ip
#   community.mysql.mysql_query:
#     login_db: wordpress
#     query: UPDATE wp_options SET autoload='no' WHERE option_id<3
