
- name: Restart mysql service
  service: name=mysql state=restarted

- name: Run RESET MASTER command which will delete all existing binary log files
  community.mysql.mysql_replication:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    mode: resetprimary

- name: Get primary binlog file name and binlog position
  community.mysql.mysql_replication:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    mode: getprimary