---
- name: Install wordpress importer
  command: sudo wp plugin install wordpress-importer --activate --allow-root --path=/var/www/acme.example.org/wordpress

- name: Import wordpress xml
  command: sudo wp import /home/ubuntu/import.xml --authors=create --path=/var/www/acme.example.org/wordpress --allow-root

- name: Update wp plugins
  command: sudo wp plugin update --allow-root --all --path=/var/www/acme.example.org/wordpress

- name: Update wp themes
  command: sudo wp theme update --allow-root --all --path=/var/www/acme.example.org/wordpress

- name: Flush wp permalinks
  command: sudo wp rewrite --allow-root flush --path=/var/www/acme.example.org/wordpress

- name: Set wp permalinks to plain
  command: sudo wp rewrite structure '' --allow-root --path=/var/www/acme.example.org/wordpress
