mariadb_version: 10.1.22

mariadb_service_name: mysql
mariadb_secure_installation: True

mariadb_root_password: changeme

# mariadb_server_path_utiles: /root/utiles


mariadb_databases:
 - wordpress


mariadb_users: []
# delete [] and define databases
# user1:
#    name: "usuario1"
#    password: "clave1"
#    priv: "*.*:ALL"
# user2:
#    name: "usuario2"
#    password: "clave2"
#    priv: "db.table:priv1,priv2"
# user3:
#    name: "usuario3"
#    password: "clave3"
#    priv: "bdpruebas.*:ALL"


# Delfi: Maybe bind should be something else. '127.0.0.1'
mariadb_options:
  bind_address: '0.0.0.0'
  performance_schema: on
  skip_name_resolve: 1
  max_connections: 100
  connect_timeout: 2
  max_allowed_packet: 10M
  innodb_buffer_pool_instances: 1
  innodb_buffer_pool_size: 100M
  innodb_log_file_size: 25M
  table_cache: 1000
  tmp_table_size: 50M
  max_heap_table_size: 50M
  query_cache_limit: 256K
  query_cache_type: 0
  query_cache_size: 0
  query_cache_min_res_unit: 2k
  join_buffer_size: 2M
  sort_buffer_size: 256K
  read_buffer_size: 128K
  read_rnd_buffer_size: 4M
  key_buffer: 500M
  slow_query_log: true
  long_query_time: 5
  log_slow_admin_statements: true
  log_queries_not_using_indexes: true


aptget_update_cache_valid_time: 3600