---
- name: Install nfs-server
  apt:
    name: nfs-kernel-server

- name: Create directory to be shared
  file:
    path: /mnt/sharedfiles
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777

- name: Transfer wp-content directory
  synchronize:
    src: /home/ubuntu/acme_wordpress_files/wp-content
    dest: /mnt/sharedfiles/
    owner: yes

- name: Copy export file
  copy:
    content: /mnt/sharedfiles/wp-content wordpress_*(rw,sync,no_subtree_check,no_root_squash)
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644

- name: Apply export file config
  shell: exportfs -a

- name: Reboot nfs server
  shell: systemctl restart nfs-kernel-server
