---
- name: install nfs-server
  apt: 
    name: nfs-kernel-server

- name: create directory to be shared
  file:
    path: /mnt/sharedfiles
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
    
- name: Copy export file
  copy:
    content: /mnt/sharedfiles 192.168.0.0/16(rw,sync,no_subtree_check)
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644

- name: Apply export file config
  shell: exportfs -a

- name: Reboot nfs server
  shell: systemctl restart nfs-kernel-server
...