---
- name: Install MySQL and other things
  hosts: wordpress
  remote_user: ubuntu 
  become: yes # Maybe needed?

  roles: 
  - common
  - dbmaster
  - dbslave

- name: Install Wordpress and dependencies
  hosts: wp
  remote_user: ubuntu
  become: yes
  vars_files:
    - ./vars/wordpress.yml

  roles:
    - common
    - wordpress