---
- name: Install MariaDB
  hosts: dbmaster
  remote_user: ubuntu 
  become: yes

  roles: 
  - common
  - mariadb

- name: Install Wordpress and dependencies
  hosts: wp
  remote_user: ubuntu
  become: yes
  vars_files:
    - ./vars/wordpress.yml

  roles:
    - common
    - wordpress