---
- name: Install and set up nfs-server
  hosts: fs
  remote_user: ubuntu
  become: yes

  roles:
    - common
    - fileserver

- name: Install MySQL and other things
  hosts: wordpress
  remote_user: ubuntu
  become: yes # Maybe needed?

  roles:
  - common
  - dbmaster
  - dbslave
  - fileclient

- name: Install Wordpress and dependencies
  hosts: wp
  remote_user: ubuntu
  become: yes
  vars_files:
    - ./vars/wordpress.yml

  roles:
    - common
    - wordpress
    - fileclient
