---
- name: Upgrade and update packages and set host file
  hosts: all
  remote_user: ubuntu
  roles:
  - common

- name: Install MariaDB
  hosts: dbmaster
  remote_user: ubuntu 
  become: yes
  roles: 
  - mariadb

- name: Install Wordpress and dependencies
  hosts: wp
  remote_user: ubuntu
  become: yes
  vars_files:
    - ./vars/wordpress.yml
  roles:
    - wordpress