---
- name: Upgrade and update packages and set host file
  hosts: all
  remote_user: ubuntu
  roles:
    - common

- name: Manage wp files on control node
  hosts: localhost
  roles:
    - controlnode

- name: Install and set up nfs-server
  hosts: fs
  remote_user: ubuntu
  become: yes
  roles:
    - fileserver

- name: Install MariaDB
  hosts: dbmaster, dbslave
  remote_user: ubuntu
  become: yes
  roles:
    - mariadb
  tags: db

- name: configure master server
  hosts: dbmaster
  remote_user: ubuntu
  become: yes
  roles:
   - dbmaster
  tags: db

- name: configure slave server
  hosts: dbslave
  remote_user: ubuntu
  become: yes
  vars_files:
    - ./roles/mariadb/defaults/main.yml
  roles:
   - dbslave
  tags: db

- name: Install Wordpress and dependencies
  hosts: wp
  remote_user: ubuntu
  become: yes
  vars_files:
    - ./vars/wordpress.yml
  roles:
    - wordpress
  tags: wp

- name: Configure and wordpress themes, plugins and permalinks
  hosts: wp[0]
  remote_user: ubuntu
  become: yes
  roles:
    - wpconfig

- name: Install prometheus
  hosts: localhost
  connection: local
  roles:
    - cloudalchemy.prometheus
  vars_files:
    - ./vars/prometheus.yml

- name: Install alertmanager
  hosts: localhost
  connection: local
  roles:
    - cloudalchemy.alertmanager
  vars_files:
    - ./vars/alertmanager.yml
